---
aws_access_key: "{{ vaulted_aws_access_key }}"
aws_secret_key: "{{ vaulted_aws_secret_key }}"
ec2_keypair: "{{ vaulted_ec2_keypair }}"

ec2_url: https://ec2.amazonaws.com
ec2_image: ami-7c491f05
ec2_instance_type: t2.micro
ec2_region: eu-west-1
ec2_group: default
ec2_internet_gateway: default-igw
